# Generated by Django 4.1 on 2022-09-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_create_wikidata_demo_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='discoverable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='share_mode',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC_READONLY', 'Public (read-only)'), ('PUBLIC_READWRITE', 'Public (read-write)')], default='PRIVATE', max_length=255),
        ),
    ]
