version: '3'
services:
  bold:
    image: egordm/bold:latest
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./storage:/storage
      - ./backend/.env:/app/.env
    networks:
      - bold-net


networks:
  bold-net: