version: '3'
services:
  postgres:
    build: ./dev/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: helloworld
      POSTGRES_MULTIPLE_DATABASES: test,develop,production
    ports:
      - 5432:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - bold-net

  blazegraph:
    image: openkbs/blazegraph-docker
    ports:
      - 9999:9999
    volumes:
      - data-blazegraph:/var/lib/blazegraph/data
      - ./storage:/storage
      - ./dev/blazegraph:/opt/blazegraph-custom
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999" ]
      interval: 3s
      timeout: 5s
      retries: 3

  meilisearch:
    image: getmeili/meilisearch:v1.7.2
    ports:
      - 7700:7700
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: "masterKey"
    volumes:
      - data-meilisearch:/meili_data


volumes:
  data-postgres:
  data-blazegraph:
  data-meilisearch:

networks:
  bold-net: