version: '3'
services:
  bold:
    image: egordm/bold:latest
    build: .
    environment:
      BLAZEGRAPH_ENABLE: on
      BLAZEGRAPH_ENDPOINT: http://blazegraph:9999
      MEILISEARCH_ENDPOINT: http://meilisearch:7700
      MEILISEARCH_MASTER_KEY: masterKey
    ports:
      - 8000:8000
    volumes:
      - ./storage:/storage
      - ./backend/.env:/app/.env
    networks:
      - bold-net
    links:
      - postgres
      - blazegraph
      - meilisearch
    depends_on:
      - postgres
      - blazegraph
      - meilisearch

  postgres:
    build: ./dev/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: helloworld
      POSTGRES_MULTIPLE_DATABASES: test,develop,production
    ports:
      - 5432:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - bold-net

  blazegraph:
    image: openkbs/blazegraph-docker
    ports:
      - 9999:9999
    volumes:
      - data-blazegraph:/var/lib/blazegraph/data
#      - ./dev/jetty.xml:/var/lib/blazegraph/conf/jetty.xml
      - ./storage:/storage
      - ./dev/blazegraph:/opt/blazegraph-custom
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999" ]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - bold-net

  meilisearch:
    image: getmeili/meilisearch:v1.7.2
    ports:
      - 7700:7700
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: "masterKey"
    volumes:
      - data-meilisearch:/meili_data
    networks:
      - bold-net


volumes:
  data-postgres:
  data-blazegraph:
  data-meilisearch:

networks:
  bold-net: