GET http://127.0.0.1:8000/api/data/yago/search_terms?limit=100&query=(Albert Einstein) AND count:[100 TO 100000]

###
POST http://127.0.0.1:8000/api/profile/yago/filtered_distribution
Content-Type: application/json

{
    "props": [
      "http://yago-knowledge.org/resource/infobox/en/ethnicity"
    ],
    "filters": [
      [
        ["http://yago-knowledge.org/resource/isCitizenOf"],
        ["http://yago-knowledge.org/resource/United_States"]
      ]
    ],
    "n_bins": 10
}

###
GET http://localhost:8000/terms/2f306b76-4347-4d68-a76c-a48b9a94bbfb/search?query=%2Bpos%3A1%20wikipedia
#GET http://localhost:8000/terms/33cb191a-b879-43ab-9667-0592acee2d21/search?query=%2Bpos%3A1


###
GET http://localhost:8000/tasks/?offset=0&limit=5&ordering=-created&state__in=SUCCESS,FAILURE


###
GET http://localhost:5820/yago/namespaces
authorization: Basic YWRtaW46YWRtaW4=

###
POST http://localhost:5820/a1KAZn4jAiX/query
authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/sparql-query
Accept: text/tsv

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
    ?iri
    (STR(?label_raw) AS ?label)
    ?count
    ?pos
    ?type
{
    {
        SELECT (?t as ?iri) (COUNT(?t) as ?count) (0 as ?pos)
        { ?t ?p ?v }
        GROUP BY ?t HAVING (?count > 1)
    } UNION {
        SELECT (?t as ?iri) (COUNT(?t) as ?count) (1 as ?pos)
        { ?s ?t ?v }
        GROUP BY ?t HAVING (?count > 1)
    } UNION {
        SELECT (?t as ?iri) (COUNT(?t) as ?count) (2 as ?pos)
        { ?s ?p ?t FILTER(?p != rdfs:label) }
        GROUP BY ?t HAVING (?count > 1)
    }

    OPTIONAL {
        ?iri rdfs:label ?label_raw.
        FILTER (STRSTARTS(lang(?label_raw), 'en'))
    }
    OPTIONAL { ?iri rdfs:type ?type }
}


###
GET https://triplydb.com/_api/search/datasets

###
GET https://api.triplydb.com/datasets/?q=poke

###
GET https://api.triplydb.com/datasets/?limit=3

###
GET https://api.triplydb.com/datasets/?limit=200

###
GET https://api.triplydb.com/datasets/academy/pokemon

### WIKIdata 2
POST https://query.wikidata.org/sparql
Content-Type: application/sparql-query
Accept: application/sparql-results+json

SELECT * {
  ?s ?p ?o
 }
LIMIT 10

### WIKIdata 2
POST https://query.wikidata.org/sparql?limit=10
Content-Type: application/sparql-query
Accept: application/sparql-results+json

SELECT * {
  ?s ?p ?o
 }
LIMIT 100

### WIKIdata 2
POST https://query.wikidata.org/sparql?limit=10
Content-Type: application/sparql-query
Accept: application/sparql-results+json

SELECT (COUNT(*) AS ?count)
WHERE { ?s ?p ?o }


### Wikidata Search
GET https://www.wikidata.org/w/api.php?action=wbsearchentities&search=gen&language=en&uselang=en&type=property&format=json&formatversion=2&errorformat=plaintext&origin=*&limit=12


### Wikidata Search2
GET https://www.wikidata.org/w/api.php?action=wbsearchentities&search=Albert&language=en&uselang=en&type=item&format=json&formatversion=2&errorformat=plaintext&origin=*&limit=12


### TriplyDB
POST https://api.triplydb.com/datasets/academy/pokemon/services/pokemon/sparql?limit=10
Content-Type: application/sparql-query
Accept: application/sparql-results+json

SELECT (COUNT(*) AS ?count)
WHERE { ?s ?p ?o }

### TriplyDB
POST https://api.triplydb.com/datasets/LaurensRietveld/got/services/got/sparql?limit=10
Content-Type: application/sparql-query
Accept: application/sparql-results+json

SELECT (COUNT(*) AS ?count)
WHERE { ?s ?p ?o }

### TriplyDB
POST https://api.triplydb.com/datasets/LaurensRietveld/got/services/got/sparql?limit=10
Content-Type: application/sparql-query
Accept: text/csv

SELECT *
WHERE { ?s ?p ?o }
LIMIT 10

### TriplyDB Search
POST https://api.triplydb.com/datasets/academy/pokemon/services/search/search
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": [
        {"simple_query_string": {
          "query": "rareness"
        }},
        {"match": {
          "http://www w3 org/1999/02/22-rdf-syntax-ns#type": "http://www.w3.org/2002/07/owl#DatatypeProperty"
        }}
      ]
    }
  }
}

###
POST https://api.triplydb.com/datasets/LaurensRietveld/got/services/search/search
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": [
        {"simple_query_string": {
          "query": "rareness"
        }},
        {"match": {
          "http://www w3 org/1999/02/22-rdf-syntax-ns#type": "http://www.w3.org/2002/07/owl#DatatypeProperty"
        }}
      ]
    }
  }
}


###
# curl -X POST
#     -H "Content-Type:application/sparql-update"
#     -H "Accept:text/html"
#     --data "select distinct ?Concept where {[] a ?Concept} LIMIT 100" http://localhost:8890/sparql
POST https://dbpedia.org/sparql?limit=10&timeout=60
Content-Type: application/sparql-query
Accept: application/sparql-results+json

SELECT (COUNT(*) AS ?count)
WHERE { ?s ?p ?o }
LIMIT 10


###
POST http://localhost:5820/rdf/query
authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/sparql-query
Accept: text/tsv

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
    ?iri
    (STR(?labelRaw) AS ?label)
    ?count
    ?pos
    ?type
    (STR(?descriptionRaw) AS ?description)
{
    {
        SELECT (?t as ?iri) (0 as ?count) (1 as ?pos)
        {
            ?t rdf:type rdf:Property
        }
    }
    UNION
    {
        SELECT (?t as ?iri) (0 as ?count) (0 as ?pos)
        {
            VALUES ?tt { rdfs:Class rdfs:Resource }
            ?t rdf:type ?tt
        }
    }
    UNION
    {
        SELECT (?t as ?iri) (0 as ?count) (2 as ?pos)
        {
            VALUES ?tt { rdfs:Class rdfs:Resource }
            ?t rdf:type ?tt
        }
    }

    OPTIONAL {
        ?iri rdfs:label ?labelRaw.
        FILTER (STRSTARTS(lang(?labelRaw), 'en') || lang(?labelRaw)='')
    }
    OPTIONAL {
        ?iri rdfs:comment ?descriptionRaw.
        FILTER (STRSTARTS(lang(?descriptionRaw), 'en') || lang(?descriptionRaw)='')
    }
    OPTIONAL { ?iri rdfs:type ?type }
}