# Generated by Django 4.0.5 on 2022-06-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.UUIDField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('RETRY', 'RETRY'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=255)),
                ('object_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
