# Generated by Django 4.0.5 on 2022-06-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltaskmeta',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('RETRY', 'RETRY'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=255),
        ),
    ]
