# Generated by Django 4.1 on 2022-08-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
